// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeSyncRun = `-- name: CompleteSyncRun :exec
UPDATE sync_runs
SET status = $2, records_in = $3, records_out = $4,
    error_message = $5, completed_at = NOW()
WHERE id = $1
`

type CompleteSyncRunParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	RecordsIn    int32       `json:"records_in"`
	RecordsOut   int32       `json:"records_out"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) CompleteSyncRun(ctx context.Context, arg CompleteSyncRunParams) error {
	_, err := q.db.Exec(ctx, completeSyncRun,
		arg.ID,
		arg.Status,
		arg.RecordsIn,
		arg.RecordsOut,
		arg.ErrorMessage,
	)
	return err
}

const createSyncRun = `-- name: CreateSyncRun :one
INSERT INTO sync_runs (job_type, status)
VALUES ($1, 'RUNNING')
RETURNING id
`

func (q *Queries) CreateSyncRun(ctx context.Context, jobType string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSyncRun, jobType)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getOrCreateCategory = `-- name: GetOrCreateCategory :one
INSERT INTO categories (slug, name, parent_id)
VALUES ($1, $2, $3)
ON CONFLICT (parent_id, slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type GetOrCreateCategoryParams struct {
	Slug     string      `json:"slug"`
	Name     string      `json:"name"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) GetOrCreateCategory(ctx context.Context, arg GetOrCreateCategoryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrCreateCategory, arg.Slug, arg.Name, arg.ParentID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const linkProductCategory = `-- name: LinkProductCategory :exec
INSERT INTO product_categories (product_id, category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkProductCategoryParams struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) LinkProductCategory(ctx context.Context, arg LinkProductCategoryParams) error {
	_, err := q.db.Exec(ctx, linkProductCategory, arg.ProductID, arg.CategoryID)
	return err
}

const updateSyncRunProgress = `-- name: UpdateSyncRunProgress :exec
UPDATE sync_runs
SET records_in = $2, records_out = $3
WHERE id = $1
`

type UpdateSyncRunProgressParams struct {
	ID         pgtype.UUID `json:"id"`
	RecordsIn  int32       `json:"records_in"`
	RecordsOut int32       `json:"records_out"`
}

func (q *Queries) UpdateSyncRunProgress(ctx context.Context, arg UpdateSyncRunProgressParams) error {
	_, err := q.db.Exec(ctx, updateSyncRunProgress, arg.ID, arg.RecordsIn, arg.RecordsOut)
	return err
}

const upsertProduct = `-- name: UpsertProduct :one
INSERT INTO products (
    parent_asin, title, brand, description, price, currency,
    image_url, product_type, condition
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (parent_asin) DO UPDATE SET
    title        = EXCLUDED.title,
    brand        = EXCLUDED.brand,
    description  = EXCLUDED.description,
    price        = EXCLUDED.price,
    currency     = EXCLUDED.currency,
    image_url    = EXCLUDED.image_url,
    product_type = EXCLUDED.product_type,
    condition    = EXCLUDED.condition,
    updated_at   = NOW()
RETURNING id, parent_asin
`

type UpsertProductParams struct {
	ParentAsin  string         `json:"parent_asin"`
	Title       string         `json:"title"`
	Brand       *string        `json:"brand"`
	Description *string        `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Currency    string         `json:"currency"`
	ImageUrl    *string        `json:"image_url"`
	ProductType *string        `json:"product_type"`
	Condition   string         `json:"condition"`
}

type UpsertProductRow struct {
	ID         pgtype.UUID `json:"id"`
	ParentAsin string      `json:"parent_asin"`
}

func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) (UpsertProductRow, error) {
	row := q.db.QueryRow(ctx, upsertProduct,
		arg.ParentAsin,
		arg.Title,
		arg.Brand,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.ImageUrl,
		arg.ProductType,
		arg.Condition,
	)
	var i UpsertProductRow
	err := row.Scan(&i.ID, &i.ParentAsin)
	return i, err
}
