// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type CartItem struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	AddedAt   pgtype.Timestamptz `json:"added_at"`
}

type Category struct {
	ID           pgtype.UUID        `json:"id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	Slug         string             `json:"slug"`
	Name         string             `json:"name"`
	ProductCount int32              `json:"product_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ChatMessage struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChatSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Title     *string            `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Collection struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CollectionProduct struct {
	CollectionID pgtype.UUID        `json:"collection_id"`
	ProductID    pgtype.UUID        `json:"product_id"`
	AddedAt      pgtype.Timestamptz `json:"added_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      *string            `json:"body"`
	IsRead    bool               `json:"is_read"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Status          string             `json:"status"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	Currency        string             `json:"currency"`
	ShippingName    *string            `json:"shipping_name"`
	ShippingAddress []byte             `json:"shipping_address"`
	PlacedAt        pgtype.Timestamptz `json:"placed_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type OrderItem struct {
	ID        pgtype.UUID    `json:"id"`
	OrderID   pgtype.UUID    `json:"order_id"`
	ProductID pgtype.UUID    `json:"product_id"`
	Quantity  int32          `json:"quantity"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
	Title     string         `json:"title"`
}

type Product struct {
	ID                 pgtype.UUID        `json:"id"`
	ParentAsin         string             `json:"parent_asin"`
	Title              string             `json:"title"`
	Brand              *string            `json:"brand"`
	Description        *string            `json:"description"`
	Price              pgtype.Numeric     `json:"price"`
	Currency           string             `json:"currency"`
	ImageUrl           *string            `json:"image_url"`
	ProductType        *string            `json:"product_type"`
	Condition          string             `json:"condition"`
	AvgRating          pgtype.Numeric     `json:"avg_rating"`
	ReviewCount        int32              `json:"review_count"`
	RatingDistribution []byte             `json:"rating_distribution"`
	PublishedStatus    string             `json:"published_status"`
	ContentHash        *string            `json:"content_hash"`
	FtsVector          interface{}        `json:"fts_vector"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ProductCategory struct {
	ProductID  pgtype.UUID `json:"product_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type ProductEmbedding struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Embedding pgvector.Vector    `json:"embedding"`
	Model     string             `json:"model"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProductFeature struct {
	ID                pgtype.UUID        `json:"id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	SenetimentScore   pgtype.Numeric     `json:"senetiment_score"`
	QualityScore      pgtype.Numeric     `json:"quality_score"`
	ReviewVelocity    pgtype.Numeric     `json:"review_velocity"`
	BrandScore        pgtype.Numeric     `json:"brand_score"`
	HelpfulnessRation pgtype.Numeric     `json:"helpfulness_ration"`
	ComputedAt        pgtype.Timestamptz `json:"computed_at"`
}

type ProductReviewsMetum struct {
	ID                 pgtype.UUID        `json:"id"`
	ProductID          pgtype.UUID        `json:"product_id"`
	ReviewCount        int32              `json:"review_count"`
	AvgRating          pgtype.Numeric     `json:"avg_rating"`
	RatingDistribution []byte             `json:"rating_distribution"`
	ReviewVelocity     pgtype.Numeric     `json:"review_velocity"`
	HelpfulnessRatio   pgtype.Numeric     `json:"helpfulness_ratio"`
	RawReviewsR2Path   *string            `json:"raw_reviews_r2_path"`
	ComputedAt         pgtype.Timestamptz `json:"computed_at"`
}

type ProductSummary struct {
	ID        pgtype.UUID        `json:"id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Pros      []string           `json:"pros"`
	Cons      []string           `json:"cons"`
	Summary   *string            `json:"summary"`
	Verdict   *string            `json:"verdict"`
	Model     *string            `json:"model"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SavedProduct struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SavedSearch struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Query     string             `json:"query"`
	Filters   []byte             `json:"filters"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SyncRun struct {
	ID           pgtype.UUID        `json:"id"`
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	RecordsIn    int32              `json:"records_in"`
	RecordsOut   int32              `json:"records_out"`
	ErrorMessage *string            `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	DisplayName  *string            `json:"display_name"`
	AvatarUrl    *string            `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}
