// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProductByID = `-- name: GetProductByID :one
SELECT id, parent_asin, title, brand, description, price, currency, image_url, product_type, condition, avg_rating, review_count, rating_distribution, published_status, content_hash, fts_vector, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ParentAsin,
		&i.Title,
		&i.Brand,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.ImageUrl,
		&i.ProductType,
		&i.Condition,
		&i.AvgRating,
		&i.ReviewCount,
		&i.RatingDistribution,
		&i.PublishedStatus,
		&i.ContentHash,
		&i.FtsVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
