// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getKnownProductsByCategory = `-- name: GetKnownProductsByCategory :many
SELECT p.parent_asin, p.id
FROM products p
JOIN product_categories pc ON pc.product_id = p.id
JOIN categories c ON c.id = pc.category_id
WHERE c.slug = $1 OR c.name = $1
`

type GetKnownProductsByCategoryRow struct {
	ParentAsin string      `json:"parent_asin"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) GetKnownProductsByCategory(ctx context.Context, slug string) ([]GetKnownProductsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getKnownProductsByCategory, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetKnownProductsByCategoryRow
	for rows.Next() {
		var i GetKnownProductsByCategoryRow
		if err := rows.Scan(&i.ParentAsin, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductAggregatesFromReviews = `-- name: UpdateProductAggregatesFromReviews :exec
UPDATE products SET avg_rating = $1, review_count = $2, updated_at = NOW()
WHERE id = $3
`

type UpdateProductAggregatesFromReviewsParams struct {
	AvgRating   pgtype.Numeric `json:"avg_rating"`
	ReviewCount int32          `json:"review_count"`
	ID          pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateProductAggregatesFromReviews(ctx context.Context, arg UpdateProductAggregatesFromReviewsParams) error {
	_, err := q.db.Exec(ctx, updateProductAggregatesFromReviews, arg.AvgRating, arg.ReviewCount, arg.ID)
	return err
}

const upsertProductReviewsMeta = `-- name: UpsertProductReviewsMeta :exec

INSERT INTO product_reviews_meta
    (product_id, review_count, avg_rating, rating_distribution,
     review_velocity, helpfulness_ratio, raw_reviews_storage_path)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (product_id) DO UPDATE SET
    review_count             = EXCLUDED.review_count,
    avg_rating                = EXCLUDED.avg_rating,
    rating_distribution        = EXCLUDED.rating_distribution,
    review_velocity            = EXCLUDED.review_velocity,
    helpfulness_ratio          = EXCLUDED.helpfulness_ratio,
    raw_reviews_storage_path   = EXCLUDED.raw_reviews_storage_path,
    computed_at                = NOW()
`

type UpsertProductReviewsMetaParams struct {
	ProductID             pgtype.UUID    `json:"product_id"`
	ReviewCount           int32          `json:"review_count"`
	AvgRating             pgtype.Numeric `json:"avg_rating"`
	RatingDistribution    []byte         `json:"rating_distribution"`
	ReviewVelocity        pgtype.Numeric `json:"review_velocity"`
	HelpfulnessRatio      pgtype.Numeric `json:"helpfulness_ratio"`
	RawReviewsStoragePath *string        `json:"raw_reviews_storage_path"`
}

// NOT currently used by reviews_ingestion.go — that worker uses raw
// pgx queries directly (see MIGRATION_GUIDE.md for why: avoiding
// hand-fabricated sqlc output that might drift from your actual
// sqlc v1.31.1 formatting). Run `sqlc generate` after adding this file
// if you want reviews.Worker rewired onto dbgen for consistency with
// catalog.Worker's pattern — that's a follow-up, not required to ship.
func (q *Queries) UpsertProductReviewsMeta(ctx context.Context, arg UpsertProductReviewsMetaParams) error {
	_, err := q.db.Exec(ctx, upsertProductReviewsMeta,
		arg.ProductID,
		arg.ReviewCount,
		arg.AvgRating,
		arg.RatingDistribution,
		arg.ReviewVelocity,
		arg.HelpfulnessRatio,
		arg.RawReviewsStoragePath,
	)
	return err
}
